
GET http://localhost:3000/ HTTP/1.1
Content-Type: application/json

{

}

####
POST http://localhost:3000/authen/authen_request HTTP/1.1
Content-Type: application/json

{
    "authen_request" : "b044ebc9f588cdf2e185311adbb79d037222adc9d9685db596c4b68055c4911f"
}

####
# After calling /authen/authen_request, copy the token from response.data.
# Then generate authenSignature in MySQL/MariaDB:
# SELECT SHA2(CONCAT(username, '&', password, '&', 'PASTE_AUTHEN_TOKEN_HERE'), 256) AS authenSignature
# FROM user_accounts
# WHERE username = 'afdol';

POST http://localhost:3000/authen/access_request HTTP/1.1
Content-Type: application/json

{
    "authen_token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFmZG9sIiwiaWF0IjoxNzg0MDk2MDg1LCJleHAiOjE3ODQxODI0ODV9.0rBQImccla6cJI_tWlXMpZL_jXeaW04tZeF0iB3BnnM",
    "authen_signature" : "4ff8d387f465619e69875e65f94e2a873f5bbf609538638e56f0e13bcfabf2c6"
}
### 
GET http://localhost:3000/skill HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0LCJ1c2VybmFtZSI6ImFmZG9sIiwiaWF0IjoxNzg0MDk2MTIxLCJleHAiOjE3ODQxODI1MjF9.Ky5e1vvde8esJD1SaaBzF9lJpSeUz_uY3S2b_lRH_Ys

### 
GET http://localhost:3000/session/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0LCJ1c2VybmFtZSI6ImFmZG9sIiwiaWF0IjoxNzg0MDk2MTIxLCJleHAiOjE3ODQxODI1MjF9.Ky5e1vvde8esJD1SaaBzF9lJpSeUz_uY3S2b_lRH_Ys
### 
GET http://localhost:3000/exercise/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0LCJ1c2VybmFtZSI6ImFmZG9sIiwiaWF0IjoxNzg0MDk2MTIxLCJleHAiOjE3ODQxODI1MjF9.Ky5e1vvde8esJD1SaaBzF9lJpSeUz_uY3S2b_lRH_Ys